name: ublue-sway-custom
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/sericea-main
image-version: latest

modules:
  - type: files
    files:
      - source: etc
      - destination: /usr/etc
      - source: xkb
      - destination: /usr/share/X11/xkb
  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
    install:
      - syncthing
      - kitty
      - zsh
      - corectrl
      - zathura
      - zathura-pdf-poppler
      - openrgb
      - SwayNotificationCenter
      - tlp
      - powertop
      - virt-manager
      - wireguard-tools
      - ufw
      - gcc
      - gcc-c++
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - containerd.io
    remove:
      - firefox
      - firefox-langpacks
      - foot
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - io.gitlab.librewolf-community
        - org.mozilla.firefox
        - com.github.tchx84.Flatseal
        - dev.vencord.Vesktop
        - org.localsend.localsend_app
        - io.freetubeapp.FreeTube
        - com.tutanota.Tutanota
        - io.mpv.Mpv
        - com.github.iwalton3.jellyfin-media-player
        - org.libreoffice.LibreOffice
        - org.keepassxc.KeePassXC
        - org.filezillaproject.Filezilla
        - com.github.IsmaelMartinez.teams_for_linux
        - com.github.xournalpp.xournalpp
        - io.github.mimbrero.WhatsAppDesktop
        - net.davidotek.pupgui2
        - org.qbittorrent.qBittorrent
        - io.missioncenter.MissionCenter
        - com.obsproject.Studio
        - net.lutris.Lutris
        - org.ryujinx.Ryujinx
        - net.pcsx2.PCSX2
        - org.prismlauncher.PrismLauncher
        - net.cozic.joplin_desktop
        - com.valvesoftware.Steam
        - org.kde.kasts
        - io.gitlab.news_flash.NewsFlash
        - com.nextcloud.desktopclient.nextcloud
        - org.gnome.World.Iotas
        - com.bitwarden.desktop
  - type: brew
    nofile-limits: true
  - type: chezmoi
    repository: "https://github.com/obispobruno/dotfiles"
  - type: justfiles
  - type: signing
  - type: systemd
    system:
      enabled:
        - syncthing.service
