---
name: ublue-sway-custom
description: Custom image based on quay.io/fedora-ostree-desktops/sway-atomic

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43

modules:
  - from-file: base/common.yml
  - from-file: common/packages.yml
  - from-file: common/default-flatpaks.yml
  - type: script
    scripts:
      - nct6687d.sh
      - new-lg4ff.sh
  - type: dnf
    repos:
      cleanup: true
      copr:
        - erikreider/SwayNotificationCenter
    install:
      packages:
        - gammastep
        - zathura
        - zathura-pdf-poppler
        - SwayNotificationCenter
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: initramfs
