---
name: ublue-sway-custom
description: Custom image based on quay.io/fedora-ostree-desktops/sway-atomic

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 42

modules:
  - from-file: base/common.yml
  - from-file: common/docker-engine.yml
  - from-file: common/libvirt.yml
  - from-file: common/default-flatpaks.yml
  - type: dnf
    repos:
      files:
        - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
        - https://negativo17.org/repos/fedora-steam.repo
    install:
      packages:
        - kitty
        - kitty-terminfo
        - alacritty
        - ghostty
        - zsh
        - corectrl
        - zathura
        - zathura-pdf-poppler
        - SwayNotificationCenter
        - tlp
        - powertop
        - gcc
        - gcc-c++
        - patch
        - zlib-devel
        - bzip2
        - bzip2-devel
        - readline-devel
        - sqlite
        - sqlite-devel
        - openssl-devel
        - tk-devel
        - libffi-devel
        - xz-devel
        - libuuid-devel
        - gdbm-libs
        - libnsl2
        - make
        - cmake
        - protobuf-devel
        - android-tools
        - steam
        - gamescope
        - mangohud
        - gamemode
        - waydroid
        - waydroid-selinux
        - gammastep
        - https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: script
    snippets:
      - "cp /usr/local/sessionmanagerplugin/bin/session-manager-plugin /usr/bin/"
      - "rm -rf /usr/lib/waydroid/data/scripts/waydroid-net.sh"
  - type: brew
    nofile-limits: true
  - type: chezmoi
    repository: "https://github.com/obispobruno/dotfiles"
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  - type: initramfs
