# image will be published to ghcr.io/<user>/<name>
name: ublue-sway-custom
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - etc: /usr/etc
      - 60-custom.just: /usr/share/ublue-os/just
      - xkb: /usr/share/X11/xkb
      - brlpdwrappermfcj410: /usr/lib/cups/filter
      - brother_mfcj410_printer_en.ppd: /usr/share/cups/model/Brother
      - brother_mfcj410_printer_en.ppd: /usr/share/ppd/Brother
      - brprintconf_mfcj410: /usr/bin
  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://negativo17.org/repos/fedora-uld.repo
    install:
      - gutenprint
      - gutenprint-cups
      - uld
      - kitty
      - kitty-terminfo
      - zsh
      - steam
      - steam-devices
      - gamescope
      - mangohud
      - corectrl
      - zathura
      - zathura-pdf-poppler
      - foomatic
      - mpv
      - wireshark
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - containerd.io
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - io.gitlab.librewolf-community
        - com.github.tchx84.Flatseal
        - dev.vencord.Vesktop
        - io.freetubeapp.FreeTube
        - com.tutanota.Tutanota
        - com.github.iwalton3.jellyfin-media-player
        - org.libreoffice.LibreOffice
        - org.keepassxc.KeePassXC
        - org.filezillaproject.Filezilla
        - com.github.IsmaelMartinez.teams_for_linux
        - com.github.xournalpp.xournalpp
        - io.github.mimbrero.WhatsAppDesktop
        - net.davidotek.pupgui2
        - org.qbittorrent.qBittorrent
        - io.missioncenter.MissionCenter
        - com.obsproject.Studio
        - org.gnome.Boxes
        - org.winehq.Wine
        - net.lutris.Lutris
        - org.ryujinx.Ryujinx
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
